# Utiliza una imagen base adecuada para Python y FastAPI
FROM python:3.11.3

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos necesarios
COPY app/ /app
COPY requirements.txt /app
COPY .env /app

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto que utiliza tu aplicación FastAPI
EXPOSE 8000



# Comando para iniciar la aplicación utilizando python3 y el archivo main.py
CMD ["python", "main.py"]

