# Utiliza una imagen base adecuada para el broker MQTT (por ejemplo, eclipse-mosquitto)
FROM eclipse-mosquitto:latest
FROM python:3.11.3

WORKDIR /mqtt

# Copia el archivo mqtt.py
COPY mqtt/ /mqtt
COPY .env .env


# Instala las dependencias
RUN pip install paho-mqtt requests configparser python-dotenv python-dateutil



# Comando para ejecutar el broker MQTT (ajústalo según el broker que estés utilizando)
CMD ["mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
